# Generated by Django 5.0.6 on 2024-06-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('admin_user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('admin_password', models.CharField(max_length=100)),
            ],
        ),
    ]
